EmployeeManager/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup', views.signup, name="signup"),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('app.urls')),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views

app_name = "app"

urlpatterns = [
    path('', views.index, name="index"),
    path('employees/', views.employee_list, name = 'employee_list'),
    path('employees/new/', views.employee_form, name = 'employee_new'),
    path('employees/<int:id>/', views.employee_form, name = 'employee_update'),
    path('search_employees', views.search_employees, name='search_employees'),
    path('employees/delete/<int:id>/', views.employee_delete, name = 'employee_delete'),
]

app/models.py
from django.db import models

class Position(models.Model):
    title = models.CharField(max_length = 50)

    def __str__(self):
        return self.title

# Create your models here.
class Employee(models.Model):
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    salary = models.IntegerField(default = 0)
    position = models.ForeignKey(Position,on_delete = models.CASCADE)
    mobile = models.CharField(max_length = 100)

app/forms.py
from django import forms
from .models import Employee
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EmployeeForm,self).__init__(*args, **kwargs)
        self.fields['position'].empty_label = "select"

class SignUpForm(UserCreationForm):
    username: forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Username'}))

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

        def __init__(self, *args, **kwargs):
            super(SignUpForm,self).__init__(*args, **kwargs)

            

    

app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import EmployeeForm, SignUpForm
from .models import Employee
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import render_to_string
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.db import connection
from collections import namedtuple


# Create your views here.
def index(request):
    return render(request, "app/index.html")

def signup(request):

    form = SignUpForm()
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('app:employee_list')
    
    return render(request, "registration/signup.html", {'form':form})


def employee_list(request):
    context = {'employee_list': Employee.objects.all()}
    return render(request, "app/employee_list.html",context)


def employee_form(request, id = 0):
    if request.method == "GET":
        if id == 0:
            form = EmployeeForm()
        else:
            employee = Employee.objects.get(pk = id)
            form = EmployeeForm(instance = employee)
        return render(request, "app/employee_form.html", {'form':form})
    else:
        if id == 0:
            form = EmployeeForm(request.POST)
        else:
            employee = Employee.objects.get(pk = id)
            form = EmployeeForm(request.POST, instance = employee)

        if form.is_valid():
            first_name = request.POST.get("first_name")
            last_name = request.POST.get("last_name")
            salary = request.POST.get("salary")
            position_id = request.POST.get("position")
            mobile = request.POST.get("mobile")

            cursor = connection.cursor()
            query = "INSERT INTO app_employee (first_name, last_name, salary, position_id, mobile) VALUES ('%s', '%s', '%s', '%s', '%s')" % (first_name, last_name, salary, position_id, mobile)
            cursor.executescript(query)

        return redirect('/employees/')


def employee_delete(request, id):
    employee = Employee.objects.get(pk = id)
    employee.delete()
    return redirect('/employees/')


@csrf_exempt
def search_employees(request):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        search_term = request.POST.get('searchTerm')

        #insecure implemen
        cursor = connection.cursor()
        query = "SELECT * FROM app_employee WHERE first_name LIKE '%s';" % search_term
        cursor.execute(query)
        print(cursor.fetchall())
        employees = namedtuplefetchall(cursor)

        html = render_to_string('app/search_employees.html', {'employee_list':employees})
        return HttpResponse(html)

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

app/templates/app/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
    crossorigin="anonymous">

    <!-- Font Awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">

    <style>
      /* To remove the down arrow by the right of the user avatar in the navbar */
      .dropdown-toggle::after {
        content: none;
      }
    </style>

    {% block head %}

    {% endblock %}
  </head>

  <body>

    <!-- Bootstrap -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
      crossorigin="anonymous">
    </script>

    <!-- jQuery for Data Tables -->
    <script
      src="https://code.jquery.com/jquery-3.6.4.js"
      integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E="
      crossorigin="anonymous">
    </script>

    <!-- JS for Data Tables -->
    <script type="text/javascript" charset="utf8"
      src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js">
    </script>

    <script type="text/javascript" charset="utf8"
      src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap5.min.js">
    </script>

    <script type="text/javascript" charset="utf8"
      src="https://cdn.datatables.net/select/1.3.3/js/dataTables.select.min.js">
    </script>

    <!-- Nav Bar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'app:index' %}">Employee Manager</a>
        <button class="navbar-toggler" type="button"
        data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02" aria-expanded="false"
        aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page"
              href="{% url 'app:employee_list' %}">Employees</a>
            </li>
          </ul>

          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown"
              aria-expanded="true">
                <div class="white-color hover-orange size-24px">
                  <span>{{ user }}</span>
                  <i class="fas fa-user"></i>
                </div>
              </a>
              <div class="dropdown-menu dropdown-menu-end">
                {% if user.is_authenticated %}
                  {% if user.is_superuser %}
                    <a class="dropdown-item" href="{% url 'signup' %}">Create User</a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                {% else %}
                  <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                {% endif %}
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    <div class="container">
      <div class="col-md-10 offset-md-1 mt-5">
        <div class="jumbotron">
          <h1 class="display-4">Employee Manager</h1>
          <p class="lead font-italic">Manage Employee Data</p>
          <hr class="my-4">
          {% block content %}
          {% endblock content %}
      </div>
      </div>
    </div>
    


  </body>
</html>

app/templates/app/employee_form.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}

{% block head %}
<title>New Employee</title>
{% endblock %}

{% block content %}
<form action="" method="post" autocomplete="off">
    {% csrf_token %}
    {{form|crispy}}

    <button type="submit" class="btn btn-success btn-lg">
        Submit
    </button>  

    <a href="{% url 'app:employee_list' %}" class="btn btn-secondary btn-lg">
        Back to list
    </a>

</form>
 
  
{% endblock content %}

app/templates/app/employee_list.html
{% extends "app/base.html" %}

{% block head %}
<title>Employee List</title>
{% endblock %}

{% block content %}
    <div class="row mb-2">
        <div class="col-md-6">
        <div style="width:50%;" class="input-group">
            <input id="searchBox" type="text" class="form-control"
            placeholder="Search Employees">
            <button class="btn btn-outline-secondary" type="button" id="searchEmployee">
            <i class="fas fa-search"></i>
            </button>
        </div>
    </div>
    
    <div id="searchOutput">
        <table id="employeeTable" class="table table-borderless">
            <thead class="border-bottom font-weight-bold">
                <tr>
                    <td>First Name</td>
                    <td>Last Name</td>
                    <td>Salary</td>
                    <td>Position</td>
                    <td>Mobile</td>
                    <td>
                        <a href="{% url 'app:employee_new' %}" class="btn btn-outline-success">
                            <i class="fas fa-plus"></i> Add New
                        </a>
                    </td>
                </tr>
            </thead>
            <tbody>
                {% for employee in employee_list %}
                    <tr>
                        <td>{{employee.first_name}}</td>
                        <td>{{employee.last_name}}</td>
                        <td>{{employee.salary}}</td>
                        <td>{{employee.position}}</td>
                        <td>{{employee.mobile}}</td>
                        <td>
                            <a href="{% url 'app:employee_update' employee.id %}" class="btn text-secondary px-0">
                                <i class="far fa-edit fa-lg"></i>
                            </a>
                            <form action="{% url 'app:employee_delete' employee.id %}" method="post" class="d-inline">
                                {% csrf_token %}
                                <button type="submit" class="btn">
                                    <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script type="text/javascript">
        $(document).ready(function() {
          $(document).on("click","#searchEmployee",function() {
            var searchTerm = $("#searchBox").val();
      
            $.ajax({
                type: "POST",
                url: "{% url 'app:search_employees' %}",
                data: {'searchTerm':searchTerm},
                success: function(response){
                  $('#searchOutput').html(response);
                }
            });
      
          });
        });
    </script>

  
{% endblock content %}

app/templates/app/index.html
{% extends "app/base.html" %}


    {% block content %}

      <div class="container">
        <div class="card mt-4">
          <div class="card-body text-center">
            <h1 class="text-center display-4">Welcome</h1>
            {% if user.is_authenticated %}
              <p>You are logged in as {{user.username}}</p>
              <div class="mb-3">
                <a href="{% url 'app:employee_list' %}" class="">View Employees</a>
              </div>
              <div class="d-grid gap-2 w-25 mx-auto">
                {% if user.is_superuser %}
                  <a href="{% url 'signup' %}" class="btn btn-primary btn-lg">Create User</a>
                {% endif %}
                <a href="{% url 'logout' %}" class="btn btn-secondary btn-lg">Logout</a>
              </div>
            {% else %}
            <a href="{% url 'login' %}" class="btn btn-primary btn-lg">Sign In</a>
            {% endif %} 
          </div>
        </div>
      </div>

    {% endblock %}

app/templates/app/search_employees.html
<table id="employeeTable" class="table table-borderless">
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>First Name</td>
            <td>Last Name</td>
            <td>Salary</td>
            <td>Position</td>
            <td>Mobile</td>
            <td>
                <a href="{% url 'app:employee_new' %}" class="btn btn-outline-success">
                    <i class="fas fa-plus"></i> Add New
                </a>
            </td>
        </tr>
    </thead>
    <tbody>
        {% for employee in employee_list %}
            <tr>
                <td>{{employee.first_name}}</td>
                <td>{{employee.last_name}}</td>
                <td>{{employee.salary}}</td>
                <td>{{employee.position}}</td>
                <td>{{employee.mobile}}</td>
                <td>
                    <a href="{% url 'app:employee_update' employee.id %}" class="btn text-secondary px-0">
                        <i class="far fa-edit fa-lg"></i>
                    </a>
                    <form action="{% url 'app:employee_delete' employee.id %}" method="post" class="d-inline">
                        {% csrf_token %}
                        <button type="submit" class="btn">
                            <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                        </button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>